spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messanger
    username: messanger
    password: messanger
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
jwt:
  secret: "tB1+UA0619nP2IVLp3DGoT0vXcxQfVoGwBGKbaB+3oY="
  access-expiration-ms: 900000        # 15 минут
  refresh-expiration-ms: 604800000    # 7 дней